init.SB.proj.table <- function(file_location, file_name){
  
  # Initialize the .hmtl file
  html_head <- cat(
    paste("<!DOCTYPE HTML>", sep = ''), "\n",
    paste("<html>", sep = ''), "\n",
    paste("<head>", sep = ''), "\n",
    "\t",
    paste("<meta charset=\"utf-8\">", sep = ''), "\n",
    "\t",
    paste("<meta http-equiv=\"Cache-control\" content=\"no-cache\" />", sep = ''), "\n",
    "\t",
    paste("<title>Projects</title>", sep = ''), "\n",
    "\t",
    paste("<style type=\"text/css\">", sep = ''), "\n",
    "\t", "\t",
    paste("@font-face {", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("font-family: \"Roadgeek2005SeriesD\";", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("src: url(\"http://panic.com/fonts/Roadgeek 2005 Series D/Roadgeek 2005 Series D.otf\");", sep = ''), "\n",
    "\t", "\t",
    paste("}", sep = ''), "\n",
    "\t", "\t",
    paste("body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,fieldset,input,textarea,p,blockquote,th,td {", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("margin: 0;", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("padding: 0;", sep = ''), "\n",
    "\t", "\t",
    paste("}", sep = ''), "\n",
    "\t", "\t",
    paste("html, body, #main{", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("overflow: hidden;", sep = ''), "\n",
    "\t", "\t",
    paste("}", sep = ''), "\n",
    "\t", "\t",
    paste("body {", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("font-family: 'Roadgeek2005SeriesD', sans-serif;", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("color: white;", sep = ''), "\n",
    "\t", "\t",
    paste("}", sep = ''), "\n",
    "\t", "\t",
    paste("body, html, #main", sep = ''), "\n",
    "\t", "\t",
    paste("{", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("background: transparent !important;", sep = ''), "\n",
    "\t", "\t",
    paste("}", sep = ''), "\n",
    "\t", "\t",
    paste("#tasks_container {", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("padding: 16px;", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("text-align: center;", sep = ''), "\n",
    "\t", "\t",
    paste("}", sep = ''), "\n",
    "\t",
    paste("</style>", sep = ''), "\n",
    paste("</head>", sep = ''), "\n",
    paste("", sep = ''), "\n",
    paste("<body onload=\"init()\">", sep = ''), "\n",
    "\t",
    paste("<div id=\"main\">", sep = ''), "\n",
    "\t", "\t",
    paste("<div id=\"tasks_container\">", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("<table class=\"legend\" style=\"padding-bottom: 5px; border-bottom: 1px solid #111;\">", sep = ''), "\n",
    "\t", "\t", "\t", "\t",
    paste("<tr>", sep = ''), "\n",
    "\t", "\t", "\t", "\t", "\t",
    paste("<td class=\"projectName\" style=\"text-align: left; width: 180px; font-size: 19px; color: rgb(256, 256, 256)\">Project</td>", sep = ''), "\n",
    "\t", "\t", "\t", "\t", "\t",
    paste("<td class=\"projectPeople\" style=\"text-align: left; width: 170px; font-size: 19px; color: rgb(256, 256, 256)\">People</td>", sep = ''), "\n",
    "\t", "\t", "\t", "\t", "\t",
    paste("<td class=\"projectNextTasks\" style=\"text-align: left; width: 220px; font-size: 19px; color: rgb(256, 256, 256)\">Next Task</td>", sep = ''), "\n",
    "\t", "\t", "\t", "\t", "\t",
    paste("<td class=\"projectNextDeliverables\" style=\"text-align: left; width: 240px; font-size: 19px; color: rgb(256, 256, 256)\">Next Deliverable</td>", sep = ''), "\n",
    "\t", "\t", "\t", "\t", "\t",
    paste("<td class=\"projectPercentComplete\" style=\"text-align: center; width: 80px; font-size: 19px; color: rgb(256, 256, 256)\">Complete</td>", sep = ''), "\n",
    "\t", "\t", "\t", "\t", "\t",
    paste("<td class=\"projectStatus\" style=\"text-align: right; width: 80px; font-size: 19px; color: rgb(256, 256, 256)\">Status</td>", sep = ''), "\n",
    "\t", "\t", "\t", "\t",
    paste("</tr>", sep = ''), "\n",
    "\t", "\t", "\t",
    paste("</table>", sep = ''), "\n",
    "\t", "\t",
    paste("</div>", sep = ''), "\n",
    "\t",
    paste("</div>", sep = ''), "\n",
    paste("</body>", sep = ''), "\n",
    paste("</html>", sep = ''),
    sep = '',
    file = paste(file_location, file_name, sep = ''),
    append = FALSE)
  
  # End function
}
