#!/usr/bin/r

## TODO -- automatically install suggested packages

## set to TRUE if you want to force updates
setwd("~/RcppBiocChecks")
forceUpdate <- FALSE

if (!require(BiocInstaller)) {
  source("http://bioconductor.org/biocLite.R")
  biocLite()
}

cat("Started at ", format(Sys.time()), "\n")
#library(parallel)

## use a directory where we can preserve downloads, etc. across runs
lib <- "~/RcppBiocChecks/libs"
Sys.setenv("R_LIBS_USER"=lib)
Sys.setenv("_R_CHECK_FORCE_SUGGESTS_"=0)

## for the borked src/Makevars of ExactNumCI
Sys.setenv("BOOSTLIB"="/usr/include")
suppressMessages(library(pkgDepTools))

countBioc <- function(vers="release") {
  deps <- makeDepGraph(paste("http://bioconductor.org/packages/", vers, "/bioc/", sep=""), type="source", dosize=FALSE)
  rcpp <- inEdges("Rcpp", deps)
  return(rcpp[[1]])
}
AP.BioC <- union( countBioc("2.14"), countBioc("release") )
res <- data.frame(pkg=AP.BioC, res=NA)

## A function to grab a package, plus dependencies.
get <- function(x, ...) {
  tryCatch(
    install.packages(x, lib=lib, destdir=normalizePath("tarballs"),
      dependencies=c("Depends", "Imports", "LinkingTo", "Suggests")
    ), error=function(e) {
      biocLite(x,
        lib=lib, destdir=normalizePath("tarballs"),
        dependencies=c("Depends", "Imports", "LinkingTo", "Suggests")
      )
    }

  )
}

#for (pi in 1:nrow(res)) {
#lres <- mclapply(1:nrow(res), mc.cores = 4, FUN=function(pi) {
exit_codes <- lapply(AP.BioC, function(p) {

  if (forceUpdate) {
    get(p)
  }

  tarballs <- sort( list.files("tarballs", full.names=TRUE, pattern=p) )

  if (!length(tarballs)) {
    cat("No tarball available for package", p, "; trying to download...\n", sep="")
    get(p)
  }

  tarballs <- sort( list.files("tarballs", full.names=TRUE, pattern=p) )
  tarball <- tarballs[1]
  cat("Using tarball '", tarball, "' for installation.\n", sep="")

  pkg <- gsub(".*/", "", tarball)
  pkg <- gsub("\\.tar\\.gz", "", pkg)
  cat("Starting check for package '", p, "'.\n", sep="")
  rc <- system(paste("R CMD check --no-manual --no-vignettes ", tarball, " > ", "logs/", pkg, ".log", sep=""))
  time <- strftime( Sys.time() )
  if (rc == 0) {
    cat("Package '", p, "' checked successfully at ", time, ".\n\n", sep="")
  } else {
    cat("Package '", p, "' failed R CMD check at ", time, ".\n\n", sep="")
  }
  return( setNames(rc, p) )
})

res <- data.frame(
  pkg=sapply(exit_codes, names),
  code=unname( unlist( exit_codes ) )
)

logs <- list.files("logs")

print(res)
write.table(res, file=paste("results/result-", strftime(Sys.time(), "%Y%m%d-%H%M%S"), ".txt", sep=""), sep=",")
save(res, file=paste("result-", strftime(Sys.time(), "%Y%m%d-%H%M%S"), ".RData", sep=""))
cat("Ended at ", format(Sys.time()), "\n")

## Collate all the most relevant results into a nice repository
res <- lapply(AP.BioC, function(pkg) {
  dir.create( file.path("results", pkg), showWarnings=FALSE, recursive=TRUE )

  ## copy the log file
  pkg_logs <- sort(list.files("logs", pattern=pkg, full.names=TRUE))
  if (length(pkg_logs)) {
    pkg_log <- pkg_logs[1]
    filename <- gsub(".*/(.*)_.*", "\\1", pkg_log)
    file.copy(pkg_log, file.path("results", pkg, paste0(filename, ".log")), overwrite=TRUE)
  }

  ## copy relevant output from R CMD check, if available
  Rcheck <- paste0(pkg, ".Rcheck")
  dest <- file.path("results", pkg, Rcheck)
  if (file.exists(Rcheck)) {
    ## copy the check and install logs, if possible
    install.log <- file.path(Rcheck, "00install.out")
    if (file.exists(install.log)) {
      file.copy(install.log, file.path("results", pkg, paste0(pkg, "-install.log")), overwrite=TRUE)
    }

    check.log <- file.path(Rcheck, "00check.log")
    if (file.exists(check.log)) {
      file.copy(check.log, file.path("results", pkg, paste0(pkg, "-check.log")), overwrite=TRUE)
    }
  }

})

## Construct a README.md file containinga summary for each package
write <- function(...) {
  cat(..., sep="\n", file="README.md", append=TRUE)
}

unlink("README.md")

write(
  "Rcpp Bioconductor Check Logs",
  "============================",
  "\n",
  paste("Constructed on", Sys.time()),
  "\n"
)

## TODO -- autogenerated output

## Move the results to a timestamped folder
time <- strftime( Sys.time(), "%Y%m%d" )
dir.create( paste0("results-", time), showWarnings=FALSE )
file.copy("results/.", paste0("results-", time), recursive=TRUE)
