library('testthat')
library('yaml')
library('foreign')

#library('reshape')
#library('plyr')
#library('stringr')
#library('ggplot2')
#library('log4r')
library(ggplot2)
library(directlabels)
library(fields)
library(car)
library(Cairo)
library(xtable)
library(stringr)
library(RColorBrewer)
library(shape)
library(Hmisc)
library(stringr)
library(lubridate)
library(MASS)
library(compiler)
library(rbenchmark)
options(stringsAsFactors = FALSE)
