# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rao_gen <- function(f, m, t, y, p) {
    .Call('recurrentR_rao_gen', PACKAGE = 'recurrentR', f, m, t, y, p)
}

t_index_gen <- function(m, t, s) {
    .Call('recurrentR_t_index_gen', PACKAGE = 'recurrentR', m, t, s)
}

t_index_inverse_gen <- function(Rt_index, s) {
    .Call('recurrentR_t_index_inverse_gen', PACKAGE = 'recurrentR', Rt_index, s)
}

t_index_query <- function(Rt_index, i, j, is_R_index = TRUE) {
    .Call('recurrentR_t_index_query', PACKAGE = 'recurrentR', Rt_index, i, j, is_R_index)
}

rao_gen_array <- function(X_value, m, t, y, Rt_index) {
    .Call('recurrentR_rao_gen_array', PACKAGE = 'recurrentR', X_value, m, t, y, Rt_index)
}

rao_export <- function(pRao) {
    .Call('recurrentR_rao_export', PACKAGE = 'recurrentR', pRao)
}

g_ij <- function(pRao_list, beta, Ri, Rj) {
    .Call('recurrentR_g_ij', PACKAGE = 'recurrentR', pRao_list, beta, Ri, Rj)
}

S <- function(pRao_list, beta) {
    .Call('recurrentR_S', PACKAGE = 'recurrentR', pRao_list, beta)
}

dS_over_dbeta <- function(pRao_list, beta) {
    .Call('recurrentR_dS_over_dbeta', PACKAGE = 'recurrentR', pRao_list, beta)
}

V1_hat <- function(pRao_list, beta) {
    .Call('recurrentR_V1_hat', PACKAGE = 'recurrentR', pRao_list, beta)
}

d_beta <- function(beta, X_value, Rt_index) {
    .Call('recurrentR_d_beta', PACKAGE = 'recurrentR', beta, X_value, Rt_index)
}

R_beta <- function(beta, X_value, Rt_index, s_upper_index) {
    .Call('recurrentR_R_beta', PACKAGE = 'recurrentR', beta, X_value, Rt_index, s_upper_index)
}

V_hat_tilde_Q_s_gen <- function(beta, X_value, Rt_index) {
    .Call('recurrentR_V_hat_tilde_Q_s_gen', PACKAGE = 'recurrentR', beta, X_value, Rt_index)
}

V_hat_tilde_R_s_gen <- function(beta, X_value, Rt_index, s_upper_index) {
    .Call('recurrentR_V_hat_tilde_R_s_gen', PACKAGE = 'recurrentR', beta, X_value, Rt_index, s_upper_index)
}

phi_i_j_hat_s_gen <- function(Q_s, R_s, V_Q, V_R) {
    .Call('recurrentR_phi_i_j_hat_s_gen', PACKAGE = 'recurrentR', Q_s, R_s, V_Q, V_R)
}

exp_X_beta_d_Lambda_0 <- function(beta, X_value, s_index_upper, dLambda_s) {
    .Call('recurrentR_exp_X_beta_d_Lambda_0', PACKAGE = 'recurrentR', beta, X_value, s_index_upper, dLambda_s)
}

X_V_2_inv_g_ij_exp_X_beta_d_Lambda_0 <- function(beta, X_value, s_index_upper, Lambda_s, dLambda_s, V2_inv, pRao_list, Rkappa_i_j_s) {
    .Call('recurrentR_X_V_2_inv_g_ij_exp_X_beta_d_Lambda_0', PACKAGE = 'recurrentR', beta, X_value, s_index_upper, Lambda_s, dLambda_s, V2_inv, pRao_list, Rkappa_i_j_s)
}

get_s_d <- function(t) {
    .Call('recurrentR_get_s_d', PACKAGE = 'recurrentR', t)
}

eval_N <- function(s, y, m) {
    .Call('recurrentR_eval_N', PACKAGE = 'recurrentR', s, y, m)
}

