library("jsonlite")
library("dplyr")
library("magrittr")
library("stringr")
library("zoo")
library("AnomalyDetection")
library("ggplot2")
library("ggmap")
library("raster")
library("rgdal")
library("rgeos")
## library("statebins")
## library("extrafont")
## font_import()