library(knitr)
library(ggplot2)
library(zoo)
library(stringr)
library(plyr)
library(reshape)
library(directlabels)
library(scales)
library(gridExtra)
library(car)
##require(devtools)
##install_github('rCharts', 'ramnathv')
library(rCharts)
require(rCharts)
require(RColorBrewer)
library(classInt)
library(lubridate)
# The development version of googleVis is necessary for the Sankey chart
library(devtools)
install_github("mages/googleVis")
require(googleVis)
theme_set(theme_bw())
options(stringsAsFactors = FALSE)