# party colors

colors = c(
  "DP" = "#B2182B",            # dark red   C. 9-10
  "PRC" = "#E41A1C",           # red        C. 11-15 / S. 13, S. 15
  "PDCI" = "#FB8072",          # l. red     C. 15
  "PDUP-DP" = "#B2182B",       # dark red   C. 7
  "SEL" = "#4DAF4A",           # green      C. 17 / S. 17
  "PDUP" = "#B2182B",          # dark red   C. 8
  "PCI" = "#E41A1C",           # red        C. 1-9
  "SIN" = "#FB8072",           # l. red     C. 9-10
  "VERD-PDCI" = "#4DAF4A",     # green      S. 15 -- FdV + PdCI
  "VERD" = "#4DAF4A",          # green      C. 13-15, S. 13-14
  "DEMSIN" = "#B3DE69",        # l. green   C. 10-11
  "M5S" = "#FFFF33",           # yellow     C. 17 / S.17
  "PD" = "#F781BF",            # pink       C. 15-17 / S. 15-17
  "AP" = "#B3DE69",            # l. green   C. 12
  "ULIVO" = "#B3DE69",         # l. green   C. 13-14 / S. 13-14
  "PSI" = "#F781BF",           # pink       C. 1-11
  "US" = "#FB8072",            # l. red     C. 1
  "RAD" = "#FFFF33",           # yellow     C. 7-11 -- includes Federal. Europ.
  "RNP" = "#FFFF33",           # yellow     C. 15
  "MARGH" = "#FFFF33",         # yellow     C. 14 / S. 14 -- Ulivist
  "ID" = "#FFFF33",            # yellow     C. 12
  "PPI" = "#053061",           # d. blue    C. 11-12 / S. 13
  "PSDI" = "#FCCDE5",          # l. pink    C. 1-11
  "IDV" = "#FF7F00",           # orange     C. 15-16 / S. 16 -- Mani Pulite
  "PRI" = "#FF7F00",           # orange     C. 1, 4-11
  "RINNOV" = "#FFFF33",        # yellow     C. 13 / S. 13 -- Ulivist
  "UDEUR" = "#01665E",         # teal       C. 13-15
  "DC" = "#053061",            # d. blue    C. 1-9
  "CCD" = "#80B1D3",           # l. blue    C. 12-13 / S. 13
  "CCD-CDU" = "#80B1D3",       # l. blue    C. 14 / S. 14 -- followed by UDC
  "SC" = "#FF7F00",            # orange     C. 17 / S. 17 -- Monti
  "CD" = "#01665E",            # teal       C. 17
  "UDC" = "#80B1D3",           # l. blue    C. 15 / S. 15 -- follows CCD-CDU
  "UDC-TP" = "#80B1D3",        # l. blue    C. 16
  "CDU" = "#8DD3C7",           # l. teal    S. 13
  "MPA" = "#01665E",           # teal       S. 14-15, 17
  "PPP" = "#FF7F00",           # orange     C. 13
  "PT" = "#01665E",            # teal       C. 16
  "RETE" = "#01665E",          # teal       C. 11
  "GAL" = "#A65628",           # brown      S. 17
  "PLI" = "#C51B7D",           # magenta    C. 1-11
  "NCD-UDC" = "#80B1D3",       # l. blue    C. 17 / S. 17 -- NCD = teal, UDC = l. blue
  "FI-PDL" = "#377EB8",        # blue       C. 12-17 / S. 13-17 -- FI 13-15, PdL 16-17
  "FLI-TP" = "#C51B7D",        # magenta    C. 16 / S. 16
  "NCD" = "#C51B7D",           # magenta S. 17
  "PDIUM" = "#01665E",         # teal       C. 3-5
  "PMP" = "#B3DE69",           # l. green   C. 2-3 (n = 1 in each)
  "FLD" = "#C51B7D",           # magenta    C. 12
  "LN" = "#984EA3",            # purple     C. 11-17 / S. 13-17
  "AN" = "#A65628",            # brown      C. 12-15 / S. 13-15
  "PNM" = "#1B9E77",           # d. green   C. 1-3
  "DN" = "#E5D8BD",            # l. brown   C. 7
  "MSI-DN" = "#A65628",        # brown      C. 2-11
  "IND" = "#AAAAAA"            # l. grey -- independent/mixed/minor
)

# party abbreviations

groups = c(
  "DP" = "Democrazia Proletaria",
  "PRC" = "P. Rifondazione Comunista",
  "PDCI" = "P. Comunisti Italiani",
  "PDUP-DP" = "P. di Unità Proletaria-Democrazia Proletaria",
  "SEL" = "Sinistra Ecologia Libertà",
  "PDUP" = "P. di Unità Proletaria",
  "PCI" = "P. Comunista Italiano",
  "SIN" = "Sinistra Indipendente",
  "VERD-PDCI" = "Verdi e Communisti",
  "VERD" = "Verdi",
  "DEMSIN" = "Democratici di Sinistra",
  "M5S" = "Movimento 5 Stelle",
  "PD" = "Partito Democratico",
  "AP" = "Alleanza dei Progressisti",
  "ULIVO" = "L'Ulivo",
  "PSI" = "P. Socialista Italiano",
  "US" = "Unita' Socialista",
  "RAD" = "Radicali",
  "RNP" = "Rosa nel Pugno",
  "MARGH" = "Margherita",
  "ID" = "I Democratici",
  "PPI" = "P. Popolare Italiano",
  "PSDI" = "P. Socialista Democratico Italiano",
  "IDV" = "Italia dei Valori",
  "PRI" = "Partito Repubblicano Italiano",
  "RINNOV" = "Rinnovamento Italiano",
  "UDEUR" = "Popolari-UDEUR",
  "DC" = "Democrazia Cristiana",
  "CCD" = "Centro Cristiano Democratico",
  "CCD-CDU" = "CCD-CDU: Biancofiore",
  "SC" = "Scelta Civica per Monti",
  "CD" = "Per l'Italia: Centro Democratico",
  "UDC" = "Unione di Centro",
  "UDC-TP" = "Unione di Centro, Terzo Polo",
  "CDU" = "Cristiani Democratici Uniti",
  "MPA" = "Movimento per le Autonomie",
  "PPP" = "Popolari per Prodi",
  "PT" = "Popolo e Territorio",
  "RETE" = "Movimento per la Democrazia – La Rete",
  "GAL" = "Grandi Autonomie e Libertà",
  "PLI" = "P. Liberale Italiano",
  "NCD-UDC" = "Area Popolare",
  "FI-PDL" = "Forza Italia (Il Popolo della Liberta')",
  "FLI-TP" = "Futuro e Libertà per l'Italia, Terzo Polo",
  "NCD" = "Nuovo Centrodestra",
  "PDIUM" = "P. Democratico Italiano di Unità Monarchica",
  "PMP" = "P. Monarchico Popolare",
  "FLD" = "Federalisti e Liberaldemocratici",
  "LN" = "Lega Nord",
  "AN" = "Alleanza Nazionale",
  "PNM" = "Partito Nazionale Monarchico",
  "DN" = "Democrazia Nazionale",
  "MSI-DN" = "Movimento Sociale Italiano–Destra Nazionale",
  "IND" = "mixed or minor group"
)

# ParlGov Left/Right scores

scores = c(
  "DP" = 0.5,          # 1424
  "PRC" = 0.9,
  "PDCI" = 1,
  "PDUP-DP" = 1,       # (1024 + 968) / 2
  "SEL" = 1.3,
  "PDUP" = 1.4,        # 968
  "PCI" = 1.6,         # 1088
  "SIN" = 1.6,         # coded like PCI (founded by some of its members)
  "VERD-PDCI" = 1.7,   # (FdV + PdCI) / 2
  "VERD" = 2.4,        # FdV
  "DEMSIN" = 2.6,
  "M5S" = 2.6,
  "PD" = 2.6,          # 382
  "AP" = 3.3,          # 1048 (centre-left coalition)
  "ULIVO" = 3.3,       # 1048 (centre-left coalition)
  "PSI" = 3.8,         # 1475
  "US" = 3.8,          # coded like PSI
  "RAD" = 4,           # 1296
  "RNP" = 4,           # PSDI + RAD (1278 / 1296) / 2
  "MARGH" = 4,
  "ID" = 4.1,
  "PPI" = 4.6,
  "PSDI" = 4.6,        # 242
  "IDV" = 4.9,
  "PRI" = 5,
  "RINNOV" = 5,
  "UDEUR" = 5.3,
  "DC" = 5.7,          # 1633
  "CCD" = 5.9,
  "CCD-CDU" = 5.9,
  "SC" = 6,
  "CD" = 6,
  "UDC" = 6.1,         # 226
  "UDC-TP" = 6.1,      # coded like UDC
  "CDU" = 6.2,         # 128
  "MPA" = 6.2,         # 1040
  "PPP" = 6.2,         # 840
  "PT" = 6.2,          # coded like MPA
  "RETE" = 6.2,        # 366
  "GAL" = 6.5,
  "PLI" = 6.5,         # 487
  "NCD-UDC" = 6.8,     # NCD (7.4) + UDC (6.1) / 2
  "FI-PDL" = 7.1,
  "FLI-TP" = 7.4,
  "NCD" = 7.4,         # 2268
  "PDIUM" = 7.4,       # 1702
  "PMP" = 7.4,         # 421
  "FLD" = 7.8,         # coded like LN (splinter)
  "LN" = 7.8,
  "AN" = 8.1,
  "PNM" = 8.7,         # 1050
  "DN" = 9.2,          # coded like MSI-DN  (though split was meant to be more moderate)
  "MSI-DN" = 9.2,      # 831
  "IND" = Inf
)

stopifnot(names(colors) == names(groups))
stopifnot(names(colors) == names(scores))
