#!/usr/bin/Rscript 

args <- commandArgs(TRUE)
pkg <- tail(args, 1L)
options( warn = 2 )
setwd( "~/git" )
system( sprintf( "rm -frv %s/src/*o", pkg ) )
suppressWarnings( Rcpp::compileAttributes(pkg) )
system( sprintf( "R CMD INSTALL %s", pkg ) )

